[env]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_flags = -I ${PROJECT_DIR}/../lib/shared
lib_deps =
    bblanchon/ArduinoJson
    mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display
    jandrassy/TelnetStream

[env:usb]
monitor_speed = 115200

[env:ota]
upload_protocol = espota
upload_port = rgb-display.local
monitor_port = socket://rgb-display.local:23
monitor_rts = 0
monitor_dtr = 0
