[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
lib_extra_dirs = ../lib
lib_deps =
    adafruit/Adafruit BME680 Library
    adafruit/Adafruit Unified Sensor
    knolleary/PubSubClient
    bblanchon/ArduinoJson
    jandrassy/TelnetStream

[env:usb]
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

[env:ota]
upload_protocol = espota
upload_port = living_room_env_sensor.local
monitor_port = socket://living_room_env_sensor.local:23
monitor_rts = 0
monitor_dtr = 0
