[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_flags = -I ${PROJECT_DIR}/../lib/shared
lib_deps =
    adafruit/Adafruit BME680 Library
    adafruit/Adafruit Unified Sensor
    knolleary/PubSubClient
    bblanchon/ArduinoJson

[env:usb]
monitor_speed = 115200

[env:ota]
upload_protocol = espota
upload_port = living_room_env_sensor.local
